apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- crd.yaml
- service-account.yaml
- cluster-role-binding.yaml
- role.yaml
- role-binding.yaml
- service.yaml
- deployment.yaml
namePrefix: profiles-
namespace: kubeflow
commonLabels:
  kustomize.component: profiles
configMapGenerator:
- name: profiles-parameters
  env: params.env
images:
- name: krishnadurai/profile-controller
  newName: krishnadurai/profile-controller
  newTag: 1.0
- name: krishnadurai/kfam
  newName: krishnadurai/kfam
  newTag: latest
vars:
- name: admin
  objref:
    kind: ConfigMap
    name: profiles-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.admin
- name: userid-header
  objref:
    kind: ConfigMap
    name: profiles-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.userid-header
- name: userid-prefix
  objref:
    kind: ConfigMap
    name: profiles-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.userid-prefix
- name: namespace
  objref:
    kind: Service
    name: kfam
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace
configurations:
- params.yaml
