apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: cert-manager-kube-system-resources
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager-kube-system-resources
      app.kubernetes.io/instance: cert-manager-kube-system-resources-v0.7.0
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/component: cert-manager-kube-system-resources
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: v0.7.0
  componentKinds:
  - group: rbac
    kind: Role
  - group: rbac
    kind: RoleBinding
  descriptor:
    type: ""
    version: "v0.11.0"
    description: "Automatically provision and manage TLS certificates in Kubernetes https://jetstack.io."
    keywords:
    - cert-manager
    links:
    - description: About
      url: "https://github.com/jetstack/cert-manager"
